plugins {
    kotlin("jvm") version "1.4.0"
    application
    id("com.github.johnrengelman.shadow") version "5.1.0"
}

group = "net.adriantodt"
version = "2.0"

repositories {
    jcenter()
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
    maven { url = uri("https://dl.bintray.com/arudiscord/aru") }
    maven { url = uri("https://dl.bintray.com/arudiscord/maven") }
    maven { url = uri("https://dl.bintray.com/arudiscord/kotlin") }
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation(kotlin("reflect"))

    implementation("pw.aru.psi:psi:3.0.0")
    implementation("pw.aru.libs:resources:1.0")
    implementation("pw.aru.libs:dice-notation:1.2")
}

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
}

configure<ApplicationPluginConvention> {
    mainClassName = "net.adriantodt.bot.Bot"
}

rootProject.run {
    file("src/main/kotlin/net/adriantodt/bot/exported/exported.kt").run {
        parentFile.mkdirs()
        createNewFile()
        writeText(
            """
@file:JvmName("BotExported")
@file:Suppress("unused")

/*
 * file "exported.kt". DO NOT EDIT MANUALLY. THIS FILE IS GENERATED BY GRADLE.
 */

package net.adriantodt.bot.exported

/**
 * Bot Version
 */
const val bot_version = "$version"
""".trim()
        )
    }
}
