@file:JvmName("BotExported")
@file:Suppress("unused")

/*
 * file "exported.kt". DO NOT EDIT MANUALLY. THIS FILE IS GENERATED BY GRADLE.
 */

package net.adriantodt.bot.exported

/**
 * Bot Version
 */
const val bot_version = "2.0"